debug osx troubles

diff --git a/tools/travis_install_osx b/tools/travis_install_osx
--- a/tools/travis_install_osx
+++ b/tools/travis_install_osx
@@ -19,15 +19,17 @@ else
   pushd ${HOME};
   rm -fr Qt
   # install-qt-osx creates the install at $PWD/Qt.
-  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt-osx ${QT_VERSION}
+  QT_CI_PACKAGES=qt.qt5.${QT_VERSION_SHORT}.clang_64,qt.qt5.${QT_VERSION_SHORT}.qtwebengine QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt-osx ${QT_VERSION}
+  if [ ! -e ${QTDIR}/bin/qmake ]; then
+    echo "ERROR: qmake not found on the installation path." >&2
+    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
+    find ${HOME}/Qt -maxdepth 3
+    cat ${HOME}/Qt/InstallationLog.txt
+    cat ${HOME}/Qt/components.xml
+    exit 1
+  fi
   popd;
 fi
 # note that qt-x.y.z.env created by install-qt-osx is not cached!
 export PATH=${QTDIR}/bin:${PATH}
-echo $PATH
-ls ${QTDIR}
-ls ${QTDIR}/bin
-find ${HOME}/Qt -maxdepth 3
-cat ${HOME}/Qt/InstallationLog.txt
-cat ${HOME}/Qt/components.xml
-unset -v QTDIR
+unset -v QT_VERSION QT_VERSION_SHORT QTDIR
