fix detatch bug, enhance debug.

diff --git a/tools/travis_install_linux_coverage b/tools/travis_install_linux_coverage
--- a/tools/travis_install_linux_coverage
+++ b/tools/travis_install_linux_coverage
@@ -3,6 +3,16 @@
 # This script is run on travis for the install stage of mac builds.
 #
 
+#debug failed install
+function debug() {
+  cat ${CACHEDIR}/qt-${QT_VERSION}.env
+  find ${CACHEDIR}/Qt -maxdepth 3 -ls
+  cat ${CACHEDIR}/Qt/InstallationLog.txt
+  cat ${CACHEDIR}/Qt/components.xml
+  echo "$1" >&2
+  exit 1
+}
+
 QT_VERSION=${1:-5.7.1}
 QT_VERSION_SHORT=$(echo ${QT_VERSION} | sed 's/\.//g')
 # older Qt releases use different package names and install locations.
@@ -24,12 +34,15 @@ else
   # install-qt creates the install at $PWD/Qt.
   QT_CI_PACKAGES=qt.${QT_VERSION_XY_SHORT}.gcc_64 QT_CI_DOWNLOADER="wget -nv -c" PATH=${TRAVIS_BUILD_DIR}/tools/qtci:${PATH} install-qt ${QT_VERSION}
   popd;
-  if [ ! -e ${QTDIR}/bin/qmake ]; then
-    echo "ERROR: qmake not found on the installation path." >&2
-    echo "Are the package names in QT_CI_PACKAGES correct?" >&2
-    find ${CACHEDIR}/Qt -maxdepth 3
-    cat ${CACHEDIR}/Qt/InstallationLog.txt
-    cat ${CACHEDIR}/Qt/components.xml
-    exit 1
-  fi
+  # validate install
+  (
+    set +e
+    source ${CACHEDIR}/qt-${QT_VERSION}.env
+    if [ "$(qmake -query QT_INSTALL_BINS)" != "${QTDIR}/bin" ]; then
+      debug "ERROR: unexpected Qt location."
+    fi
+    if [ "$(qmake -query QT_VERSION)" != "${QT_VERSION}" ]; then
+      debug "ERROR: wrong Qt version."
+    fi
+  )
 fi
