build snap based on kde-neon6 extension.
Both the CLI and GUI are supported.
The GUI map preview feature works.
The GUI translations work.
The GUI is invoked via 'gpsbabel.gpsbabelfe'.

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -16,21 +16,27 @@ confinement: strict # use 'strict' once you have the right plugs and slots
 
 apps:
   gpsbabel:
+    extensions:
+      - kde-neon-6
     plugs:
       - home
       - raw-usb
       - removable-media
       - serial-port
     command: usr/bin/gpsbabel
-
-# remap the ubuntu qt6 install directories to the snap.
-layout:
-  /usr/share/qt6:
-    symlink: $SNAP/usr/share/qt6
-  /usr/lib/qt6:
-    symlink: $SNAP/usr/lib/qt6
-  /usr/lib/x86_64-linux-gnu/qt6:
-    symlink: $SNAP/usr/lib/x86_64-linux-gnu/qt6
+  gpsbabelfe:
+    extensions:
+      - kde-neon-6
+    plugs:
+      - home
+      - removable-media
+      - network
+      - opengl
+      - wayland
+      - x11
+    command-chain:
+      - snap/command-chain/desktop-launch6
+    command: usr/bin/gpsbabelfe
 
 adopt-info: gpsbabel
 parts:
@@ -41,14 +47,13 @@ parts:
       - -DCMAKE_BUILD_TYPE=Release
       - -DGPSBABEL_WITH_ZLIB=pkgconfig
       - -DGPSBABEL_WITH_SHAPELIB=pkgconfig
+      - -DGPSBABEL_ENABLE_PCH=OFF
     cmake-generator: Ninja
     source: .
     override-pull: |
       craftctl default
       # add install command to CMakeLists.txt
-      echo "install(TARGETS gpsbabel CONFIGURATIONS Release RUNTIME DESTINATION /usr/bin)" >> CMakeLists.txt
-      # no gui
-      sed -i -e's/add_subdirectory(gui)/#add_subdirectory(gui)/' CMakeLists.txt
+      echo "install(TARGETS gpsbabel gpsbabelfe CONFIGURATIONS Release RUNTIME DESTINATION /usr/bin)" >> CMakeLists.txt
       # jam repo sha into GITHUB_SHA
       sed -i -e"/GB.SHA/i set(ENV{GITHUB_SHA} \"$(git log -1 --format=%h)\")" gbversion.cmake
       # set snap version
@@ -65,11 +70,25 @@ parts:
       - libusb-1.0-0-dev
       - pkg-config
       - libudev-dev
-      - qt6-base-dev
-      - libqt6core5compat6-dev
+      - libvulkan-dev
+      - libxkbcommon-dev
     stage-packages:
       - zlib1g
       - libshp2
       - libusb-1.0-0
-      - libqt6core6
-      - libqt6core5compat6
+
+  # https://snapcraft.io/docs/desktop-snap-size-reduction#heading--cleanup-part
+  cleanup:
+    after:
+    - gpsbabel
+    plugin: nil
+    build-snaps:
+    - core22
+    - kf6-core22
+    - kde-qt6-core22
+    override-prime: |
+      set -eux
+      for snap in "core22" "kf6-core22" "kde-qt6-core22"; do
+        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
+      done
+
